Repository QuantConnect/Lean, pull requests merged in 2019-10, with the labels that each got.

#3630 Fix GDAX entries in symbol properties database
  Data/symbol-properties/symbol-properties-database.csv
Labels: bug

#3649 Add new crypto pairs for both exchanges
  Data/symbol-properties/symbol-properties-database.csv
  Tests/Algorithm/AlgorithmTradingTests.cs
  Tests/Common/Securities/CashBuyingPowerModelTests.cs
  Tests/Engine/BrokerageTransactionHandlerTests/BrokerageTransactionHandlerTests.cs
  ToolBox/CoinApi/CoinApiSymbolMapper.cs
Labels: data-integrity

#3686 Update SG30SGD Exchange time zone
  Data/market-hours/market-hours-database.json
Labels: data-integrity

#3702 Update regression test after new crypto lot size
  Algorithm.CSharp/BasicSetAccountCurrencyAlgorithm.cs
  Algorithm.CSharp/BasicTemplateCryptoAlgorithm.cs
  Algorithm.CSharp/CancelOpenOrdersRegressionAlgorithm.cs
  Algorithm.CSharp/EmitInsightCryptoCashAccountType.cs
  Algorithm.CSharp/FractionalQuantityRegressionAlgorithm.cs
  Algorithm.CSharp/SetAccountCurrencyCashBuyingPowerModelRegressionAlgorithm.cs
  Algorithm.CSharp/WarmupConversionRatesRegressionAlgorithm.cs
Labels: bug

#3750 Feature fred custom data
  Common/Data/Custom/Fred/CBOE.cs
  Common/Data/Custom/Fred/CentralBankInterventions.cs
  Common/Data/Custom/Fred/CommercialPaper.cs
  Common/Data/Custom/Fred/Fred.cs
  Common/Data/Custom/Fred/FredApi.cs
  Common/Data/Custom/Fred/ICEBofAML.cs
  Common/Data/Custom/Fred/LIBOR.cs
  Common/Data/Custom/Fred/OECDRecessionIndicators.cs
  Common/Data/Custom/Fred/TradeWeightedIndexes.cs
  Common/Data/Custom/Fred/Wilshire.cs
  Common/QuantConnect.csproj
  Engine/DataFeeds/LiveTradingDataFeed.cs
  Engine/DataFeeds/SubscriptionDataReader.cs
  Tests/Common/Data/Custom/FredApiTest.cs
  Tests/QuantConnect.Tests.csproj
  Tests/TestData/FredVixData.json
Labels: feature
